VillageSociety/VillageSociety/Models/AccountPerson/AccountPersonEditModel.cs
using DevExpress.Web;
using Internationalization;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VillageSociety.Models
{
    public class AccountPersonEditModel : EditModel
    {
        [Display(Name = "SystemVillage", ResourceType = typeof(Translator))]
        [Required(ErrorMessageResourceType = typeof(Translator), ErrorMessageResourceName = "Required")]
        public int? VillageId { get; set; }

        [Display(Name = "FirstName", ResourceType = typeof(Translator))]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceType = typeof(Translator), ErrorMessageResourceName = "Required")]
        [StringLength(50, MinimumLength = 2, ErrorMessageResourceType = typeof(Translator), ErrorMessageResourceName = "StringLength")]
        public string FirstName { get; set; }

        [Display(Name = "LastName", ResourceType = typeof(Translator))]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceType = typeof(Translator), ErrorMessageResourceName = "Required")]
        [StringLength(50, MinimumLength = 2, ErrorMessageResourceType = typeof(Translator), ErrorMessageResourceName = "StringLength")]
        public string LastName { get; set; }

        [Display(Name = "Gender", ResourceType = typeof(Translator))]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceType = typeof(Translator), ErrorMessageResourceName = "Required")]
        public bool? IsMale { get; set; }

        [Display(Name = "Picture", ResourceType = typeof(Translator))]
        [StringLength(1024, MinimumLength = 2, ErrorMessageResourceType = typeof(Translator), ErrorMessageResourceName = "StringLength")]
        public string PicturePath { get; set; }

        [Display(Name = "Father", ResourceType = typeof(Translator))]
        public int? Father { get; set; }

        [Display(Name = "Mother", ResourceType = typeof(Translator))]
        public int? Mother { get; set; }
    }
}

VillageSociety/VillageSociety/Models/AccountPerson/AccountPersonGridModel.cs
using Core;
using Internationalization;
using Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace VillageSociety.Models
{
    public class AccountPersonGridModel : GridModel
    {
        public AccountPersonGridModel()
        {
            Settings.Columns.Add(column =>
            {
                column.FieldName = "Id";
                column.Width = Unit.Pixel(50);
            });
            Settings.Columns.Add(column =>
            {
                column.FieldName = "VillageName";
                column.Caption = Translator.SystemVillage;
            });
            Settings.Columns.Add(column =>
            {
                column.FieldName = "FirstName";                
                column.Caption = Translator.FirstName;
            });
            Settings.Columns.Add(column =>
            {
                column.FieldName = "LastName";
                column.Caption = Translator.LastName;
            });
            Settings.Columns.AddBand(band =>
            {
                band.Caption = Translator.Profile;
                band.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;

                band.Columns.Add(column =>
                {
                    column.Caption = Translator.PictureName;
                    column.SetDataItemTemplateContent(content =>
                    {
                        var picturePath = (string)DataBinder.Eval(content.DataItem, "PicturePath");
                        if (picturePath != null)
                        {
                            var viewContext = (ViewContext)HttpContext.Current.Session["ViewContext" + Name];
                            viewContext.Writer.Write(@"<a href=""" + picturePath + @""" download>" + Path.GetFileName(picturePath) + @"</a>");
                        }
                    });
                });
                band.Columns.Add(column =>
                {
                    column.Caption = Translator.Picture;
                    column.SetDataItemTemplateContent(content =>
                    {
                        var picturePath = (string)DataBinder.Eval(content.DataItem, "PicturePath");
                        if (picturePath != null)
                        {
                            var viewContext = (ViewContext)HttpContext.Current.Session["ViewContext" + Name];
                            viewContext.Writer.Write(@"<img src=""" + picturePath + @""" alt="""" style=""width: 100%"" />");
                        }
                    });
                });
            });
            Settings.Columns.AddBand(band =>
            {
                band.Caption = Translator.Father;
                band.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;

                band.Columns.Add(column =>
                {
                    column.FieldName = "FatherFirstName";
                    column.Caption = Translator.FirstName;
                });
                band.Columns.Add(column =>
                {
                    column.FieldName = "FatherLastName";
                    column.Caption = Translator.LastName;
                });
            });
            Settings.Columns.AddBand(band =>
            {
                band.Caption = Translator.Mother;
                band.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;

                band.Columns.Add(column =>
                {
                    column.FieldName = "MotherFirstName";
                    column.Caption = Translator.FirstName;
                });
                band.Columns.Add(column =>
                {
                    column.FieldName = "MotherLastName";
                    column.Caption = Translator.LastName;
                });
            });

            Data = () => IoC.Resolve<IAccountPersonService>().GetEx(p => !p.IsDeleted);
        }

        protected override void NameChanged()
        {
            base.NameChanged();

            MenuModel.AddShownMethod = @"function(s, e) {
    cmbClearAddAndSetItem(cmbVillageId" + Name + "Grid, '" + Security.VillageName + "', " + Security.VillageId.ToString() + ", " + (Security.IsSystemAdmin ? "true" : "false") + @");
}";

            MenuModel.UseStandardToolbar(false);
        }
    }
}

VillageSociety/VillageSociety/Controllers/AccountPersonController.cs
using Core;
using Service;
using Internationalization;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using VillageSociety.Models;
using AutoMapper;

namespace VillageSociety.Controllers
{
    public class AccountPersonController : BaseGridController
    {
        protected readonly IAccountPersonService service;

        public AccountPersonController(IAccountPersonService service)
        {
            this.service = service;
        }

        [PermissionAuthorize("AccountPerson", Permission.ReadAccountPerson)]
        public ActionResult Index()
        {
            return View();
        }

        [PermissionAuthorize("AccountPerson", Permission.ReadAccountPerson)]
        public ActionResult GridInit(AccountPersonGridModel model)
        {
            Session[model.Name] = model;
            return PartialView(model);
        }

        [PermissionAuthorize("AccountPerson", Permission.ReadAccountPerson)]
        public ActionResult GridPartial(AccountPersonGridModel model)
        {
            model = (AccountPersonGridModel)Session[model.Name];
            return PartialView(model);
        }

        public ActionResult DetailPartial(AccountPersonEditModel model)
        {
            return PartialView(model);
        }

        [PermissionAuthorize("AccountPerson", Permission.InsertAccountPerson)]
        public ActionResult InsertPartial(AccountPersonEditModel model)
        {
            return PartialView("EditPartial", model);
        }

        [HttpPost]
        [PermissionAuthorize("AccountPerson", Permission.InsertAccountPerson)]
        public ActionResult Insert(AccountPersonEditModel model)
        {
            JsonResultModel jsonModel = new JsonResultModel();

            if (ModelState.IsValid)
            {
                var item = new AccountPerson();
                try
                {
                    Mapper.DynamicMap(model, item);

                    if (!Security.IsSystemAdmin)
                    {
                        item.VillageId = Security.VillageId;
                    }

                    service.Insert(item.WithInsertDefaults());
                    service.Save();

                    jsonModel.Result = new { Id = item.Id, Texts = new string[] { item.FirstName, item.LastName } };
                }
                catch (Exception ex)
                {
                    jsonModel = service.ExceptionToJsonResult(ex, item, model.IsNewRecord);
                    if (jsonModel == null)
                    {
                        jsonModel.Exception = "Error";
                        jsonModel.Result = new { Message = Translator.PleaseTellTheProgrammersAboutTheError + "<br />" + HtmlStringFactory.ExceptionError(ex) };
                    }
                }
            }
            else
            {
                jsonModel.Exception = "Error";
                jsonModel.Result = new { Message = Translator.PleaseTellTheProgrammersAboutTheError + "<br />" + HtmlStringFactory.ModelStateError(ModelState) };
            }

            return Json(jsonModel);
        }

        [PermissionAuthorize("AccountPerson", Permission.UpdateAccountPerson)]
        public ActionResult UpdatePartial(AccountPersonEditModel model)
        {
            var item = service.GetById(model.Id);
            Mapper.DynamicMap(item, model);

            return PartialView("EditPartial", model);
        }

        [HttpPost]
        [PermissionAuthorize("AccountPerson", Permission.UpdateAccountPerson)]
        public ActionResult Update(AccountPersonEditModel model)
        {
            var jsonModel = new JsonResultModel();

            if (ModelState.IsValid)
            {
                var item = new AccountPerson();
                try
                {
                    Mapper.DynamicMap(model, item);

                    if (!Security.IsSystemAdmin)
                    {
                        item.VillageId = Security.VillageId;
                    }

                    service.Update(item.WithUpdateDefaults());
                    service.Save();

                    jsonModel.Result = new { Id = item.Id, Texts = new string[] { item.FirstName, item.LastName } };
                }
                catch (Exception ex)
                {
                    jsonModel = service.ExceptionToJsonResult(ex, item, model.IsNewRecord);
                    if (jsonModel == null)
                    {
                        jsonModel.Exception = "Error";
                        jsonModel.Result = new { Message = Translator.PleaseTellTheProgrammersAboutTheError + "<br />" + HtmlStringFactory.ExceptionError(ex) };
                    }
                }
            }
            else
            {
                jsonModel.Exception = "Error";
                jsonModel.Result = new { Message = Translator.PleaseTellTheProgrammersAboutTheError + "<br />" + HtmlStringFactory.ModelStateError(ModelState) };
            }

            return Json(jsonModel);
        }

        public ActionResult Submit(string json)
        {
            var jo = JObject.Parse(json);
            string submit = jo.Value<string>("Submit");

            if (submit == "Export")
            {
                return Export(json);
            }

            return null;
        }

        [PermissionAuthorize("AccountPerson", Permission.ExportAccountPerson)]
        public override ActionResult Export(string json)
        {
            return base.Export(json);
        }

        [PermissionAuthorize("AccountPerson", Permission.InsertAccountPerson, Permission.UpdateAccountPerson)]
        public ActionResult VillageIdPartial(AccountPersonEditModel model)
        {
            return PartialView(model);
        }

        [PermissionAuthorize("AccountPerson", Permission.InsertAccountPerson, Permission.UpdateAccountPerson)]
        public ActionResult FatherPartial(AccountPersonEditModel model)
        {
            return PartialView(model);
        }

        [PermissionAuthorize("AccountPerson", Permission.InsertAccountPerson, Permission.UpdateAccountPerson)]
        public ActionResult MotherPartial(AccountPersonEditModel model)
        {
            return PartialView(model);
        }

    }
}

VillageSociety/VillageSociety/Controllers/PopupController.cs
using DevExpress.Web.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VillageSociety.Models;

namespace VillageSociety.Controllers
{
    public class PopupController : Controller
    {
        public ActionResult HtmlPartial(HtmlPopupModel model)
        {
            return PartialView(model);
        }

        public ActionResult ActionPartial(ActionPopupModel model)
        {
            return PartialView(model);
        }

        public ActionResult ActionRoutePartial(ActionPopupModel model)
        {
            if (model.ModelData == null)
            {
                if (model.ModelFullName != null)
                {
                    model.ModelData = JsonConvert.DeserializeObject(model.ModelJson, Type.GetType(model.ModelFullName));
                }
            }

            return PartialView("ActionPartial", model);
        }

        public ActionResult SelectSingleFilePartial(SelectSingleFileModel model)
        {
            if (!Directory.Exists(model.RootFolder))
            {
                string[] splits = model.RootFolder.Split('/');

                for (int i = splits.Length - 2; i >= 0; i--)
                {
                    var field = splits[i + 1];
                    var entity = splits[i];

                    var type = Type.GetType("Entity." + entity + ", Entity");

                    if (type != null)
                    {
                        var pi = type.GetProperties().SingleOrDefault(p => p.Name == field);

                        if (pi != null)
                        {
                            Directory.CreateDirectory(Server.MapPath(model.RootFolder));
                            break;
                        }
                    }
                }
            }

            Session[model.Name] = model;
            return PartialView(model);
        }

        public ActionResult SelectSingleFileManagerPartial(SelectSingleFileModel model)
        {
            model = (SelectSingleFileModel)Session[model.Name];
            return PartialView(model);
        }

        public FileStreamResult SelectSingleFileManagerDownloadRoute(SelectSingleFileModel model)
        {
            return FileManagerExtension.DownloadFiles("fmn" + model.Name, model.RootFolder);
        }
    }
}

VillageSociety/VillageSociety/Views/AccountPerson/EditPartial.cshtml
@model AccountPersonEditModel

@{
    string controllerName = ViewContext.RequestContext.RouteData.Values["controller"].ToString();
}

@Html.Action("ActionPartial", "Popup", new ActionPopupModel
{
    Name = Model.Name + "Edit"
})

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "frm" + Model.Name + "Edit", style = "width: 100%; height: 100%;" }))
{
    <div id="divEditTable@(Model.Name)" class="Table" style="width: 100%; height: 100%">
        <div>
            <div style="height: 100%">
                <div class="EditForm" style="width: 100%">
                    <div>
                        <div>
                            @Html.DevExpress().LabelFor(m => m.VillageId, lbls =>
                            {
                                lbls.ControlStyle.Wrap = DefaultBoolean.False;
                            }).GetHtml()
                        </div>
                        <div>
                            <div>
                                @Html.Partial("VillageIdPartial", Model)
                            </div>
                            <div>
                                @Html.Action("ComboBoxMenuPartial", "EditForm", new ComboBoxMenuModel("SystemVillage")
                                {
                                    ComboBoxName = "cmbVillageId",
                                    ModelName = Model.Name
                                })
                            </div>
                        </div>
                    </div>
                    <div>
                        <div>
                            @Html.DevExpress().LabelFor(m => m.FirstName, lbls =>
                            {
                                lbls.ControlStyle.Wrap = DefaultBoolean.False;
                            }).GetHtml()
                        </div>
                        <div>
                            @Html.DevExpress().TextBoxFor(m => m.FirstName, txbs =>
                            {
                                txbs.Name = "txb" + txbs.Name + Model.Name;
                                txbs.Width = Unit.Percentage(100);
                                txbs.ShowModelErrors = true;
                                txbs.Properties.ValidationSettings.Assign(ValidationSettingsFactory.Standard);
                            }).GetHtml()
                        </div>
                    </div>
                    <div>
                        <div>
                            @Html.DevExpress().LabelFor(m => m.LastName, lbls =>
                            {
                                lbls.ControlStyle.Wrap = DefaultBoolean.False;
                            }).GetHtml()
                        </div>
                        <div>
                            @Html.DevExpress().TextBoxFor(m => m.LastName, txbs =>
                            {
                                txbs.Name = "txb" + txbs.Name + Model.Name;
                                txbs.Width = Unit.Percentage(100);
                                txbs.ShowModelErrors = true;
                                txbs.Properties.ValidationSettings.Assign(ValidationSettingsFactory.Standard);
                            }).GetHtml()
                        </div>
                    </div>
                    <div>
                        <div>
                            @Html.DevExpress().LabelFor(m => m.IsMale, lbls =>
                            {
                                lbls.ControlStyle.Wrap = DefaultBoolean.False;
                            }).GetHtml()
                        </div>
                        <div>
                            @Html.DevExpress().RadioButtonListFor(m => m.IsMale, rbls =>
                            {
                                rbls.Name = "rbl" + rbls.Name + Model.Name;
                                rbls.ShowModelErrors = true;
                                rbls.Properties.RepeatDirection = RepeatDirection.Horizontal;
                                rbls.Properties.ValidationSettings.Assign(ValidationSettingsFactory.Standard);

                                rbls.Properties.Items.Add(Translator.Male, 1, "~/Content/Icon/Male/16.png");
                                rbls.Properties.Items.Add(Translator.Female, 0, "~/Content/Icon/Female/16.png");
                            }).GetHtml()
                        </div>
                    </div>
                    <div>
                        <div>
                            @Html.DevExpress().LabelFor(m => m.PicturePath, lbls =>
                            {
                                lbls.ControlStyle.Wrap = DefaultBoolean.False;
                            }).GetHtml()
                        </div>
                        <div>
                            @Html.Action("SelectSingleFilePartial", "Popup", new SelectSingleFileModel
                            {
                                Name = "PicturePath" + Model.Name,
                                Width = Unit.Pixel(800),
                                Height = Unit.Pixel(600),
                                AllowedFileExtensions = new string[] { ".jpg", ".png", ".bmp", ".gif" },
                                RootFolder = "/Content/Image/AccountPerson",
                                MaxUploadSize = 512000,
                                MinImageWidth = 200,
                                MaxImageWidth = 200,
                                MinImageHeight = 230,
                                MaxImageHeight = 230,
                                OkScript = @"function(s, e) {
    var path = '/Content/Image/AccountPerson/' + fmnPicturePath" + Model.Name + @".GetSelectedFile().name;
    btePicturePath" + Model.Name + @".SetValue(path);
    pucPicturePath" + Model.Name + @".Hide();
}"
                            })
                            @Html.DevExpress().ButtonEditFor(m => m.PicturePath, btes =>
                            {
                                btes.Name = "bte" + btes.Name + Model.Name;
                                btes.Width = Unit.Percentage(100);
                                btes.ReadOnly = true;
                                btes.ShowModelErrors = true;
                                btes.Properties.ValidationSettings.Assign(ValidationSettingsFactory.Standard);

                                btes.Properties.Buttons.Add("...");

                                btes.Properties.ClientSideEvents.ButtonClick = @"function(s, e) {
    pucPicturePath" + Model.Name + @".Show();
}";
                                btes.Properties.ClientSideEvents.KeyDown = @"function(s ,e) {
    var keyCode = e.htmlEvent.keyCode;
    if (keyCode == 8 || keyCode == 46) {
        s.SetValue(null);
    }
}";
                            }).GetHtml()
                        </div>
                    </div>
                    <div>
                        <div>
                            @Html.DevExpress().LabelFor(m => m.Father, lbls =>
                            {
                                lbls.ControlStyle.Wrap = DefaultBoolean.False;
                            }).GetHtml()
                        </div>
                        <div>
                            <div>
                                @Html.Partial("FatherPartial", Model)
                            </div>
                            <div>
                                @Html.Action("ComboBoxMenuPartial", "EditForm", new ComboBoxMenuModel("AccountPerson")
                                {
                                    ComboBoxName = "cmbFather",
                                    ModelName = Model.Name,
                                    AddShownMethod = @"function(s, e) {
    cmbClearAddAndSetItem(cmbVillageId" + Model.Name + "Edit, '" + Security.VillageName + "', " + Security.VillageId.ToString() + ", " + (Security.IsSystemAdmin ? "true" : "false") + @");
    rblIsMale" + Model.Name + @"Edit.SetValue(1);
    rblIsMale" + Model.Name + @"Edit.SetEnabled(false);
}",
                                    EditShownMethod = @"function(s, e) {
    var cmb = cmbFather" + Model.Name + @";
    var rblIsMale = window['rblIsMale" + Model.Name + @"Edit' + cmb.GetValue()];
    rblIsMale.SetValue(1);
    rblIsMale.SetEnabled(false);
}"
                                })
                            </div>
                        </div>
                    </div>
                    <div>
                        <div>
                            @Html.DevExpress().LabelFor(m => m.Mother, lbls =>
                            {
                                lbls.ControlStyle.Wrap = DefaultBoolean.False;
                            }).GetHtml()
                        </div>
                        <div>
                            <div>
                                @Html.Partial("MotherPartial", Model)
                            </div>
                            <div>
                                @Html.Action("ComboBoxMenuPartial", "EditForm", new ComboBoxMenuModel("AccountPerson")
                                {
                                    ComboBoxName = "cmbMother",
                                    ModelName = Model.Name,
                                    AddShownMethod = @"function(s, e) {
    rblIsMale" + Model.Name + @"Edit.SetValue(0);
    rblIsMale" + Model.Name + @"Edit.SetEnabled(false);
}",
                                    EditShownMethod = @"function(s, e) {
    var cmb = cmbMother" + Model.Name + @";
    var rblIsMale = window['rblIsMale" + Model.Name + @"Edit' + cmb.GetValue()];
    rblIsMale.SetValue(0);
    rblIsMale.SetEnabled(false);
}"

                                })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div style="height: 0px">
                <div class="EditFormToolbar" style="width: 100%">
                    <div>
                        <div>
                            @Html.DevExpress().Button(btns =>
                            {
                                btns.Name = "btnSave" + Model.Name;
                                btns.Text = Translator.Save;
                                btns.Images.Image.Url = "~/Content/Icon/Save/16.png";

                                btns.ClientSideEvents.Init = @"function(s, e) {
    setTimeout(function(){ $.validator.unobtrusive.parse('#frm" + Model.Name + @"Edit'); }, 100);

    s.cpData = function() {
        return {" + (Model.IsNewRecord ? @"
            IsNewRecord: true," : @"
            Id: " + Model.Id.ToString() + ",") + @"
            VillageId: cmbVillageId" + Model.Name + @".GetValue(),
            FirstName: txbFirstName" + Model.Name + @".GetValue(),
            LastName: txbLastName" + Model.Name + @".GetValue(),
            IsMale: rblIsMale" + Model.Name + @".GetValue(),
            PicturePath: btePicturePath" + Model.Name + @".GetValue(),
            Mother: cmbMother" + Model.Name + @".GetValue(),
            Father: cmbFather" + Model.Name + @".GetValue()
        };
    };

    s.cpSuccessMethod = " + Model.SuccessMethod + @";
}";

                                btns.ClientSideEvents.Click = @"function(s, e) {
    var formValid = $('#frm" + Model.Name + @"Edit').validate().form();
    if (formValid)
    {
        EditFormAjaxPost({
            Url: '/" + controllerName + "/" + (Model.IsNewRecord ? "Insert" : "Update") + @"',
            RestoreUrl: '/" + controllerName + @"/Restore',
            Data: JSON.stringify(s.cpData()),
            Id: " + (Model.IsNewRecord ? "null" : Model.Id.ToString()) + @",
            SuccessMethod: function(jsonResult) {
                s.cpSuccessMethod(jsonResult);
            }
        });
    }

}";
                                }).GetHtml()
                        </div>
                        <div>
                            @Html.DevExpress().Button(btns =>
                            {
                                btns.Name = "btnCancel" + Model.Name;
                                btns.Text = Translator.Cancel;
                                btns.Images.Image.Url = "~/Content/Icon/Cancel/16.png";
                                btns.ClientSideEvents.Init = @"function(s, e) {
    s.cpCancelMethod = " + Model.CancelMethod + @";
}";
                                btns.ClientSideEvents.Click = @"function(s, e) {
    s.cpCancelMethod();
}";
                            }).GetHtml()

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
}

VillageSociety/VillageSociety/Views/AccountPerson/FatherPartial.cshtml
@model AccountPersonEditModel

@{
    string controllerName = ViewContext.RequestContext.RouteData.Values["controller"].ToString();
    var repository = IoC.Resolve<IAccountPersonService>();

    var comboBox = Html.DevExpress().ComboBoxFor(m => m.Father, cmbs =>
    {
        cmbs.CallbackRouteValues = new { Controller = controllerName, Action = cmbs.Name + "Partial", Name = Model.Name };
        cmbs.Name = "cmb" + cmbs.Name + Model.Name;
        cmbs.Width = Unit.Percentage(100);
        cmbs.ShowModelErrors = true;
        cmbs.Properties.ValidationSettings.Assign(ValidationSettingsFactory.Standard);

        cmbs.Properties.DropDownStyle = DropDownStyle.DropDown;
        cmbs.Properties.CallbackPageSize = 15;
        cmbs.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;

        cmbs.Properties.ValueField = "Id";
        cmbs.Properties.ValueType = typeof(int);
        cmbs.Properties.TextFormatString = "{0} {1}";

        cmbs.Properties.Columns.Add("FirstName", Translator.FirstName, Unit.Percentage(50));
        cmbs.Properties.Columns.Add("LastName", Translator.LastName, Unit.Percentage(50));
    }).BindList((args) =>
    {
        int skip = args.BeginIndex;
        int take = args.EndIndex - args.BeginIndex + 1;

        return repository
            .Get(p => !p.IsDeleted && p.IsMale && (p.FirstName + " " + p.LastName).Contains(args.Filter))
            .OrderBy(p => p.Id)
            .Skip(skip)
            .Take(take)
            .ToList();
    }, (args) =>
    {
        int id;
        if (args.Value == null || !int.TryParse(args.Value.ToString(), out id))
            return null;
        return repository
            .Get(p => !p.IsDeleted && p.Id == id)
            .Take(1)
            .ToList();            
    });
    
    if (Model.Father.HasValue)
    {
        comboBox.BindList(repository.Get(p => !p.IsDeleted && p.Id == Model.Father.Value).ToList());
    }

    comboBox.GetHtml();
}

VillageSociety/VillageSociety/Views/AccountPerson/GridInit.cshtml
@model AccountPersonGridModel

@{
    string controllerName = ViewContext.RequestContext.RouteData.Values["controller"].ToString();
}

@Html.Action("ActionPartial", "Popup", new ActionPopupModel
{
    Name = Model.Name + "Grid"
})

@Html.Action("GridPartial", controllerName, Model)